#!/bin/bash


if [ "$#" -ne 2 ]; then
    echo "Usage: $0 fichier.cpp fichier.o"
    exit 1
fi


fichier_cpp="$1"
fichier_o="$2"


chemin_inclusion1="/home/makipoea/Documents/prepa/tipe/programme/Slic3r_but_with_better_infill/xs/src/libslic3r"
chemin_inclusion2="/home/makipoea/Documents/prepa/tipe/programme/Slic3r_but_with_better_infill/xs/src"


g++ -I "$chemin_inclusion1" -I "$chemin_inclusion2" -c "$fichier_cpp" -o "$fichier_o"

